version: '3.8'

services:
  service.jekyll:
    container_name: jekyll
    build:
      context: ../ # Project Directory. The current path in a Dockerfile will be set to the context, NOT the directory where Dockerfile is.
      dockerfile: docker/jekyll/Dockerfile.jekyll # Relative to the context
    working_dir: /home/beomseochoi/project
    volumes:
      - ~/.ssh:/root/.ssh
      - ../:/home/beomseochoi/project
      
    ports: 
      - 4000:4000
    tty: true